version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "jquery",
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"